//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP2022
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PP2022Entities : DbContext
    {
        public PP2022Entities()
            : base("name=PP2022Entities")
        {
        }

        private static PP2022Entities _context;

        public static PP2022Entities GetContext()
        {
            if (_context == null)
                _context = new PP2022Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brak> Braks { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanySklad> CompanySklads { get; set; }
        public virtual DbSet<Deistviya> Deistviyas { get; set; }
        public virtual DbSet<Rabotniki> Rabotnikis { get; set; }
        public virtual DbSet<RabotnikType> RabotnikTypes { get; set; }
        public virtual DbSet<Sklad> Sklads { get; set; }
        public virtual DbSet<SkladRabotniki> SkladRabotnikis { get; set; }
        public virtual DbSet<SkladTovar> SkladTovars { get; set; }
        public virtual DbSet<Sostoyanie> Sostoyanies { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tovar> Tovars { get; set; }
        public virtual DbSet<TypeDeistvie> TypeDeistvies { get; set; }
        public virtual DbSet<Zacaz> Zacazs { get; set; }
        public virtual DbSet<Zacazchik> Zacazchiks { get; set; }
        public virtual DbSet<ZacazTovar> ZacazTovars { get; set; }
    }
}
