//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deistviya
    {
        public int ID { get; set; }
        public int IDRabotnik { get; set; }
        public int IDDeistvie { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Rabotniki Rabotniki { get; set; }
        public virtual TypeDeistvie TypeDeistvie { get; set; }
    }
}
