//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rabotniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rabotniki()
        {
            this.Companies = new HashSet<Company>();
            this.Companies1 = new HashSet<Company>();
            this.Deistviyas = new HashSet<Deistviya>();
            this.SkladRabotnikis = new HashSet<SkladRabotniki>();
            this.Zacazs = new HashSet<Zacaz>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Familia { get; set; }
        public string Otchestvo { get; set; }
        public string Phone { get; set; }
        public int IDType { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Zarplata { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deistviya> Deistviyas { get; set; }
        public virtual RabotnikType RabotnikType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkladRabotniki> SkladRabotnikis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zacaz> Zacazs { get; set; }
    }
}
