//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZacazTovar
    {
        public int ID { get; set; }
        public int IDZacaz { get; set; }
        public int IDTovar { get; set; }
        public int KolvoTovar { get; set; }
    
        public virtual Tovar Tovar { get; set; }
        public virtual Zacaz Zacaz { get; set; }
    }
}
