//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zacaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zacaz()
        {
            this.ZacazTovars = new HashSet<ZacazTovar>();
        }
    
        public int ID { get; set; }
        public int IDZacazchik { get; set; }
        public int IDRabotnik { get; set; }
        public int Cost { get; set; }
        public System.DateTime DateZacaz { get; set; }
        public System.DateTime DateOzidaetsya { get; set; }
        public int IDSostoyanie { get; set; }
    
        public virtual Rabotniki Rabotniki { get; set; }
        public virtual Sostoyanie Sostoyanie { get; set; }
        public virtual Zacazchik Zacazchik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZacazTovar> ZacazTovars { get; set; }
    }
}
